#!/bin/python3

# import random.choice for selecting computer's choice.
from random import *

usr_choice = input('Rock(r), Paper(p), Scissor(s)? \nEnter your choice : ')

options = 'rps'

#Rules: You and the computer both choose rock, paper or scissors. The winner is decided by these rules :
    #1. Rock blunts scissors
    #2. Paper covers rock
    #3. Scissors cut paper

if usr_choice in options:
  comp_choice = choice(options)
  print('Computer Choose : ',comp_choice)
  if(usr_choice == comp_choice):
    print('DRAW')
  elif(usr_choice =='r'):
    if(comp_choice == 'p'):
      print('Computer Wins')
    else:
      print('Hurray ! You Wins..')
  elif(usr_choice == 'p'):
    if(comp_choice == 'r'):
      print('Hurray ! You Wins..')
    else:
      print('Computer Wins')
  elif(usr_choice == 's'):
    if(comp_choice == 'r'):
      print('Computer Wins')
    else:
      print('Hurray ! You Wins..')
else :
  print('Invalid choice')
  
